export const POI = [
    {
        name: 'Martin Luther King Jr.',
        img: "/assets/img/Martin_Luther_King_Jr..jpg",
        short: `Martin Luther King Jr. <br> <br>(born Michael King Jr.; January 15, 1929 – April 4, 1968) was an American Christian minister and activist who became the most visible spokesperson and leader in the civil rights movement from 1955 until his assassination in 1968. <br> <br> King is best known for advancing civil rights through nonviolence and civil disobedience, inspired by his Christian beliefs and the nonviolent activism of Mahatma Gandhi.`,
        description: `Martin Luther King Jr. (born Michael King Jr.; January 15, 1929 – April 4, 1968) was an American Christian minister and activist who became the most visible spokesperson and leader in the civil rights movement from 1955 until his assassination in 1968. King is best known for advancing civil rights through nonviolence and civil disobedience, inspired by his Christian beliefs and the nonviolent activism of Mahatma Gandhi.
                        King led the 1955 Montgomery bus boycott and later became the first president of the Southern Christian Leadership Conference(SCLC).As president of the SCLC, he led an unsuccessful 1962 struggle against segregation in Albany, Georgia, and helped organize the nonviolent 1963 protests in Birmingham, Alabama.King helped organize the 1963 March on Washington, where he delivered his famous "I Have a Dream" speech on the steps of the Lincoln Memorial.
                        On October 14, 1964, King won the Nobel Peace Prize for combating racial inequality through nonviolent resistance.In 1965, he helped organize the Selma to Montgomery marches.In his final years, he expanded his focus to include opposition towards poverty, capitalism, and the Vietnam War.FBI Director J.Edgar Hoover considered him a radical and made him an object of the FBI's COINTELPRO from 1963 on. FBI agents investigated him for possible communist ties, recorded his extramarital liaisons and reported on them to government officials, and, in 1964, mailed King a threatening anonymous letter, which he interpreted as an attempt to make him commit suicide.
                    King was planning a national occupation of Washington, D.C., to be called the Poor People's Campaign, when he was assassinated on April 4 in Memphis, Tennessee. His death was followed by riots in many U.S. cities. Allegations that James Earl Ray, the man convicted of killing King, had been framed or acted in concert with government agents persisted for decades after the shooting. King was posthumously awarded the Presidential Medal of Freedom and the Congressional Gold Medal. Martin Luther King Jr. Day was established as a holiday in cities and states throughout the United States beginning in 1971; the holiday was enacted at the federal level by legislation signed by President Ronald Reagan in 1986. Hundreds of streets in the U.S. have been renamed in his honor, and a county in Washington was rededicated for him. The Martin Luther King Jr. Memorial on the National Mall in Washington, D.C., was dedicated in 2011.`,
        date: 'January 10, 1957 – April 4, 1968',
        inserted: "20/10/2020",
        user: "AGB",
    },
    {
        name: 'Robert F. Williams and the debate on nonviolence',
        img: "/assets/img/debate.jpg",
        short: `The Jim Crow 
         system employed "terror as a means of social control," with the most organized manifestations being the Ku Klux Klan and their collaborators in local police departments. <br><br> This violence played a key role in blocking the progress of the civil rights movement in the late 1950s. Some black organizations in the South began practicing armed self-defense. The first to do so openly was the Monroe, North Carolina, chapter of the NAACP led by Robert F. Williams. Williams had rebuilt the chapter after its membership was terrorized out of public life by the Klan. He did so by encouraging a new, more working-class membership to arm itself thoroughly and defend against attack. When Klan nightriders attacked the home of NAACP member Albert Perry in October 1957, Williams' militia exchanged gunfire with the stunned Klansmen, who quickly retreated. The following day, the city council held an emergency session and passed an ordinance banning KKK motorcades. <br> <br> One year later, Lumbee Indians in North Carolina would have a similarly successful armed stand-off with the Klan (known as the Battle of Hayes Pond) which resulted in KKK leader James W. "Catfish" Cole being convicted of incitement to riot.`,
        description: `The Jim Crow system employed "terror as a means of social control," with the most organized manifestations being the Ku Klux Klan and their collaborators in local police departments. This violence played a key role in blocking the progress of the civil rights movement in the late 1950s. Some black organizations in the South began practicing armed self-defense. The first to do so openly was the Monroe, North Carolina, chapter of the NAACP led by Robert F. Williams. Williams had rebuilt the chapter after its membership was terrorized out of public life by the Klan. He did so by encouraging a new, more working-class membership to arm itself thoroughly and defend against attack. When Klan nightriders attacked the home of NAACP member Albert Perry in October 1957, Williams' militia exchanged gunfire with the stunned Klansmen, who quickly retreated. The following day, the city council held an emergency session and passed an ordinance banning KKK motorcades. One year later, Lumbee Indians in North Carolina would have a similarly successful armed stand-off with the Klan (known as the Battle of Hayes Pond) which resulted in KKK leader James W. "Catfish" Cole being convicted of incitement to riot.
        After the acquittal of several white men charged with sexually assaulting black women in Monroe, Williams announced to United Press International reporters that he would "meet violence with violence" as a policy. Williams' declaration was quoted on the front page of The New York Times, and The Carolina Times considered it "the biggest civil rights story of 1959". NAACP National chairman Roy Wilkins immediately suspended Williams from his position, but the Monroe organizer won support from numerous NAACP chapters across the country. Ultimately, Wilkins resorted to bribing influential organizer Daisy Bates to campaign against Williams at the NAACP national convention and the suspension was upheld. The convention nonetheless passed a resolution which stated: "We do not deny, but reaffirm the right of individual and collective self-defense against unlawful assaults." Martin Luther King Jr. argued for Williams' removal, but Ella Baker and WEB Dubois both publicly praised the Monroe leader's position.
        Williams—along with his wife, Mabel Williams continued to play a leadership role in the Monroe movement, and to some degree, in the national movement. The Williamses published The Crusader, a nationally circulated newsletter, beginning in 1960, and the influential book Negroes With Guns in 1962. Williams did not call for full militarization in this period, but "flexibility in the freedom struggle." Williams was well-versed in legal tactics and publicity, which he had used successfully in the internationally known "Kissing Case" of 1958, as well as nonviolent methods, which he used at lunch counter sit-ins in Monroe—all with armed self-defense as a complementary tactic.
        Williams led the Monroe movement in another armed stand off with white supremacists during an August 1961 Freedom Ride; he had been invited to participate in the campaign by Ella Baker and James Forman of the Student Nonviolent Coordinating Committee (SNCC). The incident (along with his campaigns for peace with Cuba) resulted in him being targeted by the FBI and prosecuted for kidnapping; he was cleared of all charges in 1976. Meanwhile, armed self-defense continued discreetly in the Southern movement with such figures as SNCC's Amzie Moore, Hartman Turnbow, and Fannie Lou Hamer all willing to use arms to defend their lives from nightrides. Taking refuge from the FBI in Cuba, the Willamses broadcast the radio show Radio Free Dixie throughout the eastern United States via Radio Progresso beginning in 1962. In this period, Williams advocated guerilla warfare against racist institutions and saw the large ghetto riots of the era as a manifestation of his strategy.
        University of North Carolina historian Walter Rucker has written that "the emergence of Robert F Williams contributed to the marked decline in anti-black racial violence in the U.S....After centuries of anti-black violence, African Americans across the country began to defend their communities aggressively—employing overt force when necessary. This in turn evoked in whites real fear of black vengeance..." This opened up space for African Americans to use nonviolent demonstration with less fear of deadly reprisal Of the many civil rights activists who share this view, the most prominent was Rosa Parks. Parks gave the eulogy at Williams' funeral in 1996, praising him for "his courage and for his commitment to freedom," and concluding that "The sacrifices he made, and what he did, should go down in history and never be forgotten."`,
        date: '1959–1964',
        inserted: "20/10/2020",
        user: "AGB",
    },
    {
        name: 'George Raymond Jr',
        img: "/assets/img/George_Raymond_Mug.jpg",
        short: `George Raymond Jr. (January 1, 1943 – March 8, 1973) was an African-American civil rights activist, a member of the Mississippi Freedom Democratic Party, a Freedom Rider, and head of the Congress of Racial Equality in Mississippi in the 1960s. <br> <br> Raymond influenced many of Mississippi's most known activists, such as Anne Moody, C. O. Chinn, and Annie Devine to join the movement and was influential in many of Mississippi's most notable Civil Rights activities such as a Woolworth's lunchcounter sit-in and protests in Jackson, Mississippi, Meredith Mississippi March, and Freedom Summer. Raymond fought for voting rights and equality for African Americans within society amongst other things. `,
        description: `Mississippi burning trial
    The Mississippi burning trial involved the 1964 murders of Chaney, Goodman, and Schwerner, three political activists during the American Civil Rights Movement. The murders of James Chaney, a 21-year-old black man from Meridian, Mississippi; Andrew Goodman, a 20-year-old Jewish anthropology student from New York City; and Michael Schwerner, a 24-year-old Jewish CORE organizer and former social worker also from New York, symbolized the risks of participating in the Civil Rights Movement in the South during what became known as "Freedom Summer", dedicated to voter registration.
        A widespread belief exists that George Raymond was the target that day. Mississippi burning trial testimonies state that the station wagon that Schwerner, Goodman and Chaney were murdered in belonged to Raymond. It was planned that Raymond drive that day but last minute changes occurred. Schwerner, Goodman and Chaney may have been casualties. `,
        date: 'January 1, 1943 - 	March 8, 1973 (aged 30) ',
        inserted: "20/10/2020",
        user: "AGB",
    },
    {
        name: 'James Leonard Farmer Jr.',
        img: "/assets/img/James_L_Farmer_Jr.jpg",
        short: `James Leonard Farmer Jr. (January 12, 1920 – July 9, 1999) was an American civil rights activist and leader in the Civil Rights Movement "who pushed for nonviolent protest to dismantle segregation, and served alongside Martin Luther King Jr." He was the initiator and organizer of the first Freedom Ride in 1961, which eventually led to the desegregation of interstate transportation in the United States.`,
        description: `James Leonard Farmer Jr. (January 12, 1920 – July 9, 1999) was an American civil rights activist and leader in the Civil Rights Movement "who pushed for nonviolent protest to dismantle segregation, and served alongside Martin Luther King Jr." He was the initiator and organizer of the first Freedom Ride in 1961, which eventually led to the desegregation of interstate transportation in the United States.
    In 1942, Farmer co-founded the Committee of Racial Equality in Chicago along with George Houser, James R. Robinson, Samuel E. Riley, Bernice Fisher, Homer Jack, and Joe Guinn. It was later called the Congress of Racial Equality (CORE), and was dedicated to ending racial segregation in the United States through nonviolence. Farmer served as the national chairman from 1942 to 1944.
    By the 1960s, Farmer was known as "one of the Big Four civil rights leaders in the 1960s, together with King, NAACP chief Roy Wilkins and Urban League head Whitney Young."`,
        date: '1959–1964',
        inserted: "20/10/2020",
        user: "AGB",
    },
];